### ISSUE TITLE
reset form without arguments when exist initialValues

### ISSUE THREAD

**Issue by borm** [final-form/final-form#128] opened 2018-05-11 11:04 UTC
Why i can`t full reset my form when initialValues is exist?

https://codesandbox.io/s/4xq2qpzw79

https://github.com/final-form/final-form/blob/master/src/FinalForm.js#L680

**Comment by jannisg** [comment] 2018-05-28 06:03
I'm not sure what you mean?

If you are referring to click the reset button not setting all fields to "empty" but instead using your `initialValues` then this is due to the sandbox you linked running `final-form@4.2.0`, if you upgrade it to `4.6.1` by clicking the little refresh icon it will reset the form to completely empty, ignoring your `initialValues`.

**Comment by erikras** [comment] 2018-05-28 13:54
This is more or less a duplicate of #127.

**Closed by erikras** 2018-05-28 13:54 UTC
