### ISSUE TITLE
Feature request: can toPath provide similar functions to lodash.toPath

### ISSUE THREAD

**Issue by lqxu** [final-form/final-form#377] opened 2020-08-24 11:11 UTC
### Are you submitting a **bug report** or a **feature request**?
feature request

### What is the current behavior?

1. I use Field's name like this:
```
<Field name="a['a.b.c']" />
```
2. I will get values like this: 
```
a: {
  a: {
    b: {
      c: someValue
    }
  }
}
```
3. I actually want to this: 
```
a: {
  "a.b.c": someValue
}
```

### What is the expected behavior?

yeah, I want something like `lodash.toPath`, to support such a data structure:
```
a: {
  'a.b.c': 'key will include dots'
}
```

**Comment by gertdreyer** [comment] 2023-03-02 20:02
Duplicate of #273

**Closed by gertdreyer** 2023-03-02 20:02 UTC
